export const ROUTES = {
  HOME: '/',
  ADMIN: '/admin',
  ADMIN_USERS: '/admin/usuarios',
  ADMIN_COURSES: '/admin/cursos',
  ADMIN_SUBJECTS: '/admin/materias',
  DASHBOARD: '/dashboard',
  PROJECTS: '/proyectos',
  projectConfig: (id: string) => `/proyectos/${id}/config`,
  LOGIN: '/login',
  REGISTER: '/register',
  RECOVER_PASSWORD: '/recuperar-contrasena',
  CALENDARY: '/calendario',
  PREFERENCES: '/preferencias',
} as const;
