-- Tabla de eventos de calendario (separada de tareas_grupo / Kanban)

CREATE TABLE IF NOT EXISTS eventos_calendario (
  id_evento integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_grupo integer NOT NULL REFERENCES grupos_proyectos(id_grupo) ON DELETE CASCADE,
  titulo_evento varchar(150) NOT NULL,
  descripcion_evento text,
  fecha_evento date NOT NULL,
  prioridad_evento varchar DEFAULT 'Media'
    CHECK (prioridad_evento IN ('Baja', 'Media', 'Alta')),
  id_creado_por uuid NOT NULL REFERENCES usuarios(id_usuario),
  fecha_creacion timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_eventos_calendario_fecha
  ON eventos_calendario (fecha_evento);

CREATE INDEX IF NOT EXISTS idx_eventos_calendario_grupo
  ON eventos_calendario (id_grupo);

ALTER TABLE eventos_calendario ENABLE ROW LEVEL SECURITY;

-- Lectura: dueño del proyecto o integrante del grupo
CREATE POLICY eventos_calendario_select_access ON eventos_calendario
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM proyecto_profesor pp
      WHERE pp.id_grupo = eventos_calendario.id_grupo
        AND pp.id_profesor = auth.uid()
    )
    OR EXISTS (
      SELECT 1 FROM grupo_estudiante ge
      WHERE ge.id_grupo = eventos_calendario.id_grupo
        AND ge.id_usuario = auth.uid()
    )
  );

-- Inserción: dueño o integrante; el creador debe ser el usuario autenticado
CREATE POLICY eventos_calendario_insert_access ON eventos_calendario
  FOR INSERT TO authenticated
  WITH CHECK (
    id_creado_por = auth.uid()
    AND (
      EXISTS (
        SELECT 1 FROM proyecto_profesor pp
        WHERE pp.id_grupo = eventos_calendario.id_grupo
          AND pp.id_profesor = auth.uid()
      )
      OR EXISTS (
        SELECT 1 FROM grupo_estudiante ge
        WHERE ge.id_grupo = eventos_calendario.id_grupo
          AND ge.id_usuario = auth.uid()
      )
    )
  );

-- RPC: crea evento verificando acceso (patrón create_tarea_grupo)
CREATE OR REPLACE FUNCTION public.create_evento_calendario(
  p_id_grupo integer,
  p_titulo varchar,
  p_fecha_evento date,
  p_descripcion text DEFAULT NULL,
  p_prioridad varchar DEFAULT 'Media'
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_row eventos_calendario%ROWTYPE;
  v_is_member boolean;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'No autenticado';
  END IF;

  IF p_fecha_evento IS NULL THEN
    RAISE EXCEPTION 'La fecha del evento es obligatoria';
  END IF;

  SELECT EXISTS (
    SELECT 1 FROM proyecto_profesor WHERE id_profesor = v_uid AND id_grupo = p_id_grupo
    UNION
    SELECT 1 FROM grupo_estudiante WHERE id_usuario = v_uid AND id_grupo = p_id_grupo
  ) INTO v_is_member;

  IF NOT v_is_member THEN
    RAISE EXCEPTION 'No tenés acceso a este proyecto';
  END IF;

  INSERT INTO eventos_calendario (
    id_grupo,
    titulo_evento,
    descripcion_evento,
    fecha_evento,
    prioridad_evento,
    id_creado_por
  ) VALUES (
    p_id_grupo,
    trim(p_titulo),
    NULLIF(trim(p_descripcion), ''),
    p_fecha_evento,
    p_prioridad,
    v_uid
  )
  RETURNING * INTO v_row;

  RETURN row_to_json(v_row);
END;
$$;

GRANT EXECUTE ON FUNCTION public.create_evento_calendario(integer, varchar, date, text, varchar) TO authenticated;
