CREATE TABLE IF NOT EXISTS public.cursos (
  id_curso integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_curso varchar NOT NULL,
  anio_lectivo integer NOT NULL,
  especialidad varchar
);

CREATE TABLE IF NOT EXISTS public.cursos_usuarios_asignados (
  id_curso_usuario integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_curso integer NOT NULL REFERENCES public.cursos(id_curso) ON DELETE CASCADE,
  id_usuario uuid NOT NULL REFERENCES public.usuarios(id_usuario),
  rol_en_curso varchar NOT NULL,
  UNIQUE (id_curso, id_usuario)
);

CREATE TABLE IF NOT EXISTS public.materias (
  id_materia integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_materia varchar NOT NULL,
  id_curso integer NOT NULL REFERENCES public.cursos(id_curso) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS public.materia_profesor (
  id_materia_profesor integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_materia integer NOT NULL REFERENCES public.materias(id_materia) ON DELETE CASCADE,
  id_profesor uuid NOT NULL REFERENCES public.usuarios(id_usuario),
  UNIQUE (id_materia, id_profesor)
);

ALTER TABLE public.cursos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cursos_usuarios_asignados ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.materias ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.materia_profesor ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS cursos_anio_lectivo_idx
  ON public.cursos (anio_lectivo);

CREATE INDEX IF NOT EXISTS cursos_usuarios_asignados_curso_idx
  ON public.cursos_usuarios_asignados (id_curso);

CREATE INDEX IF NOT EXISTS cursos_usuarios_asignados_usuario_idx
  ON public.cursos_usuarios_asignados (id_usuario);

CREATE INDEX IF NOT EXISTS materias_curso_idx
  ON public.materias (id_curso);

CREATE INDEX IF NOT EXISTS materia_profesor_materia_idx
  ON public.materia_profesor (id_materia);

CREATE INDEX IF NOT EXISTS materia_profesor_profesor_idx
  ON public.materia_profesor (id_profesor);
