CREATE TABLE IF NOT EXISTS public.asistencias (
  id_asistencia bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_curso integer NOT NULL REFERENCES public.cursos(id_curso) ON DELETE CASCADE,
  id_usuario uuid NOT NULL REFERENCES public.usuarios(id_usuario) ON DELETE CASCADE,
  fecha date NOT NULL DEFAULT CURRENT_DATE,
  estado text NOT NULL DEFAULT 'Presente'
    CHECK (estado IN ('Presente', 'Ausente', 'Tardanza', 'Justificado')),
  observaciones text,
  id_registrado_por uuid REFERENCES public.usuarios(id_usuario),
  creado_en timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_asistencias_curso_fecha
  ON public.asistencias (id_curso, fecha);

CREATE UNIQUE INDEX IF NOT EXISTS asistencias_curso_usuario_fecha_idx
  ON public.asistencias (id_curso, id_usuario, fecha);

ALTER TABLE public.asistencias ENABLE ROW LEVEL SECURITY;
