-- Nota final individual por integrante del proyecto (pestaña Calificaciones).
--
-- Acceso solo vía `createAdminClient()` (service role) desde Express, igual que `huellas`:
-- RLS habilitado SIN policies = deny-by-default para anon/authenticated.
-- El control de permisos vive en el código Express (assertCanAccessGroup + canGradeProject).

CREATE TABLE IF NOT EXISTS public.calificaciones_proyecto (
  id_calificacion bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_grupo integer NOT NULL REFERENCES public.grupos_proyectos(id_grupo) ON DELETE CASCADE,
  id_usuario uuid NOT NULL REFERENCES public.usuarios(id_usuario) ON DELETE CASCADE,
  nota numeric(4,2) CHECK (nota IS NULL OR (nota >= 0 AND nota <= 10)),
  id_calificado_por uuid REFERENCES public.usuarios(id_usuario) ON DELETE SET NULL,
  creado_en timestamptz NOT NULL DEFAULT now(),
  actualizado_en timestamptz NOT NULL DEFAULT now(),
  UNIQUE (id_grupo, id_usuario)
);

CREATE INDEX IF NOT EXISTS idx_calificaciones_proyecto_grupo
  ON public.calificaciones_proyecto (id_grupo);

ALTER TABLE public.calificaciones_proyecto ENABLE ROW LEVEL SECURITY;

-- Supabase recarga la caché de PostgREST al detectar DDL vía event trigger,
-- pero la señal se pierde ocasionalmente: la forzamos explícitamente.
NOTIFY pgrst, 'reload schema';
