-- Asistencia general de ingreso de PROFESORES (no por curso/materia).
--
-- Flujo: el ESP32/AS608 identifica una huella (fingerprint_id = usuarios.huella_id)
-- y el backend determina fecha/hora/estado y persiste la marcación. La ausencia NO se
-- materializa a las 00:00: se calcula al leer según `configuracion_asistencia`.
--
-- Acceso solo vía `createAdminClient()` (service role) desde Express, igual que
-- `huellas` y `calificaciones_proyecto`: RLS habilitado SIN policies.

-- ---------------------------------------------------------------------------
-- Configuración (fila única id = 1). Queda preparada para ampliarse.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.configuracion_asistencia (
  id smallint PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  hora_entrada time NOT NULL DEFAULT '08:00',
  tolerancia_minutos integer NOT NULL DEFAULT 10 CHECK (tolerancia_minutos >= 0 AND tolerancia_minutos <= 240),
  minutos_ausencia integer NOT NULL DEFAULT 120 CHECK (minutos_ausencia >= 0 AND minutos_ausencia <= 720),
  -- Días laborables en ISO: 1=Lunes ... 7=Domingo. Por defecto Lunes a Viernes.
  dias_laborables smallint[] NOT NULL DEFAULT '{1,2,3,4,5}',
  actualizado_en timestamptz NOT NULL DEFAULT now(),
  id_actualizado_por uuid REFERENCES public.usuarios(id_usuario) ON DELETE SET NULL
);

INSERT INTO public.configuracion_asistencia (id)
VALUES (1)
ON CONFLICT (id) DO NOTHING;

ALTER TABLE public.configuracion_asistencia ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------------
-- Marcaciones (una fila por profesor y día). `hora_entrada` NULL = corrección
-- manual sin hora (p. ej. Ausente/Justificado).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.asistencias_profesores (
  id_asistencia_profesor bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario uuid NOT NULL REFERENCES public.usuarios(id_usuario) ON DELETE CASCADE,
  fecha date NOT NULL DEFAULT CURRENT_DATE,
  hora_entrada time,
  estado text NOT NULL DEFAULT 'Presente'
    CHECK (estado IN ('Presente', 'Tardanza', 'Ausente', 'Justificado')),
  metodo_registro text NOT NULL DEFAULT 'Huella'
    CHECK (metodo_registro IN ('Huella', 'Manual')),
  huella_id integer,
  id_registrado_por uuid REFERENCES public.usuarios(id_usuario) ON DELETE SET NULL,
  observaciones text,
  creado_en timestamptz NOT NULL DEFAULT now(),
  actualizado_en timestamptz NOT NULL DEFAULT now(),
  UNIQUE (id_usuario, fecha)
);

CREATE INDEX IF NOT EXISTS idx_asistencias_profesores_fecha
  ON public.asistencias_profesores (fecha);

CREATE INDEX IF NOT EXISTS idx_asistencias_profesores_usuario_fecha
  ON public.asistencias_profesores (id_usuario, fecha DESC);

ALTER TABLE public.asistencias_profesores ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------------
-- Auditoría de correcciones: conserva el valor previo, el nuevo, quién y por qué.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.asistencias_profesores_ajustes (
  id_ajuste bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_asistencia_profesor bigint NOT NULL REFERENCES public.asistencias_profesores(id_asistencia_profesor) ON DELETE CASCADE,
  estado_anterior text,
  hora_entrada_anterior time,
  estado_nuevo text NOT NULL,
  hora_entrada_nuevo time,
  motivo text NOT NULL,
  id_modificado_por uuid REFERENCES public.usuarios(id_usuario) ON DELETE SET NULL,
  creado_en timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_asistencias_profesores_ajustes_asistencia
  ON public.asistencias_profesores_ajustes (id_asistencia_profesor);

ALTER TABLE public.asistencias_profesores_ajustes ENABLE ROW LEVEL SECURITY;

-- Forzamos la recarga de la caché de PostgREST (a veces se pierde la señal DDL).
NOTIFY pgrst, 'reload schema';
