-- 022 — Favoritos por usuario + calendario (roles, edición/borrado, horas, recurrencia)
--
-- Contexto:
--   * `grupos_proyectos.es_favorito` era un booleano global y solo el dueño podía
--     cambiarlo. Se reemplaza por `proyecto_favorito` (un favorito por usuario).
--   * Las policies de `eventos_calendario` y el RPC solo cubrían dueño/integrante;
--     quedaban afuera el profesor asignado (`proyecto_profesor_asignado`) y el admin.

-- ---------------------------------------------------------------------------
-- ¿El usuario puede ver/operar un proyecto? (manager: admin/dueño/asignado, o integrante)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.can_view_proyecto(p_id_grupo integer)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT public.can_manage_proyecto(p_id_grupo)
  OR EXISTS (
    SELECT 1 FROM grupo_estudiante ge
    WHERE ge.id_grupo = p_id_grupo
      AND ge.id_usuario = auth.uid()
  );
$$;

REVOKE ALL ON FUNCTION public.can_view_proyecto(integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.can_view_proyecto(integer) TO authenticated;

-- ---------------------------------------------------------------------------
-- Favoritos por usuario
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.proyecto_favorito (
  id_favorito bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_grupo integer NOT NULL REFERENCES public.grupos_proyectos(id_grupo) ON DELETE CASCADE,
  id_usuario uuid NOT NULL REFERENCES public.usuarios(id_usuario) ON DELETE CASCADE,
  creado_en timestamptz NOT NULL DEFAULT now(),
  UNIQUE (id_grupo, id_usuario)
);

CREATE INDEX IF NOT EXISTS idx_proyecto_favorito_usuario
  ON public.proyecto_favorito (id_usuario);

ALTER TABLE public.proyecto_favorito ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS pf_select_own ON public.proyecto_favorito;
CREATE POLICY pf_select_own ON public.proyecto_favorito
  FOR SELECT TO authenticated
  USING (id_usuario = auth.uid());

DROP POLICY IF EXISTS pf_insert_own ON public.proyecto_favorito;
CREATE POLICY pf_insert_own ON public.proyecto_favorito
  FOR INSERT TO authenticated
  WITH CHECK (id_usuario = auth.uid() AND can_view_proyecto(id_grupo));

DROP POLICY IF EXISTS pf_delete_own ON public.proyecto_favorito;
CREATE POLICY pf_delete_own ON public.proyecto_favorito
  FOR DELETE TO authenticated
  USING (id_usuario = auth.uid());

-- Backfill: los favoritos globales previos pasan al dueño del proyecto.
INSERT INTO public.proyecto_favorito (id_grupo, id_usuario)
SELECT g.id_grupo, pp.id_profesor
FROM public.grupos_proyectos g
JOIN public.proyecto_profesor pp ON pp.id_grupo = g.id_grupo
WHERE g.es_favorito = true
ON CONFLICT (id_grupo, id_usuario) DO NOTHING;

-- `grupos_proyectos.es_favorito` queda como columna deprecada (sin uso por la app).

-- ---------------------------------------------------------------------------
-- Calendario: horas + preparación de recurrencia
-- ---------------------------------------------------------------------------
ALTER TABLE public.eventos_calendario
  ADD COLUMN IF NOT EXISTS hora_inicio time,
  ADD COLUMN IF NOT EXISTS hora_fin time,
  ADD COLUMN IF NOT EXISTS recurrencia varchar NOT NULL DEFAULT 'Ninguna';

ALTER TABLE public.eventos_calendario DROP CONSTRAINT IF EXISTS eventos_calendario_recurrencia_check;
ALTER TABLE public.eventos_calendario ADD CONSTRAINT eventos_calendario_recurrencia_check
  CHECK (recurrencia IN ('Ninguna', 'Diaria', 'Semanal', 'Mensual'));

ALTER TABLE public.eventos_calendario DROP CONSTRAINT IF EXISTS eventos_calendario_horas_check;
ALTER TABLE public.eventos_calendario ADD CONSTRAINT eventos_calendario_horas_check
  CHECK (hora_inicio IS NULL OR hora_fin IS NULL OR hora_fin > hora_inicio);

-- Policies: incluir profesor asignado/admin (can_view_proyecto) + UPDATE/DELETE.
DROP POLICY IF EXISTS eventos_calendario_select_access ON public.eventos_calendario;
CREATE POLICY eventos_calendario_select_access ON public.eventos_calendario
  FOR SELECT TO authenticated
  USING (id_creado_por = auth.uid() OR can_view_proyecto(id_grupo));

DROP POLICY IF EXISTS eventos_calendario_insert_access ON public.eventos_calendario;
CREATE POLICY eventos_calendario_insert_access ON public.eventos_calendario
  FOR INSERT TO authenticated
  WITH CHECK (id_creado_por = auth.uid() AND can_view_proyecto(id_grupo));

DROP POLICY IF EXISTS eventos_calendario_update_access ON public.eventos_calendario;
CREATE POLICY eventos_calendario_update_access ON public.eventos_calendario
  FOR UPDATE TO authenticated
  USING (id_creado_por = auth.uid() OR can_manage_proyecto(id_grupo))
  WITH CHECK (can_view_proyecto(id_grupo));

DROP POLICY IF EXISTS eventos_calendario_delete_access ON public.eventos_calendario;
CREATE POLICY eventos_calendario_delete_access ON public.eventos_calendario
  FOR DELETE TO authenticated
  USING (id_creado_por = auth.uid() OR can_manage_proyecto(id_grupo));

-- RPC de creación: valida prioridad/fecha/horas y usa can_view_proyecto (incluye admin/asignado).
DROP FUNCTION IF EXISTS public.create_evento_calendario(integer, varchar, date, text, varchar);

CREATE OR REPLACE FUNCTION public.create_evento_calendario(
  p_id_grupo integer,
  p_titulo varchar,
  p_fecha_evento date,
  p_descripcion text DEFAULT NULL,
  p_prioridad varchar DEFAULT 'Media',
  p_hora_inicio time DEFAULT NULL,
  p_hora_fin time DEFAULT NULL,
  p_recurrencia varchar DEFAULT 'Ninguna'
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_row eventos_calendario%ROWTYPE;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'No autenticado';
  END IF;

  IF p_titulo IS NULL OR trim(p_titulo) = '' THEN
    RAISE EXCEPTION 'El título del evento es obligatorio';
  END IF;

  IF p_fecha_evento IS NULL THEN
    RAISE EXCEPTION 'La fecha del evento es obligatoria';
  END IF;

  IF p_prioridad IS NULL OR p_prioridad NOT IN ('Baja', 'Media', 'Alta') THEN
    RAISE EXCEPTION 'Prioridad inválida';
  END IF;

  IF p_recurrencia IS NULL OR p_recurrencia NOT IN ('Ninguna', 'Diaria', 'Semanal', 'Mensual') THEN
    RAISE EXCEPTION 'Recurrencia inválida';
  END IF;

  IF p_hora_inicio IS NOT NULL AND p_hora_fin IS NOT NULL AND p_hora_fin <= p_hora_inicio THEN
    RAISE EXCEPTION 'La hora de fin debe ser posterior a la de inicio';
  END IF;

  IF NOT public.can_view_proyecto(p_id_grupo) THEN
    RAISE EXCEPTION 'No tenés acceso a este proyecto';
  END IF;

  INSERT INTO eventos_calendario (
    id_grupo,
    titulo_evento,
    descripcion_evento,
    fecha_evento,
    prioridad_evento,
    hora_inicio,
    hora_fin,
    recurrencia,
    id_creado_por
  ) VALUES (
    p_id_grupo,
    trim(p_titulo),
    NULLIF(trim(p_descripcion), ''),
    p_fecha_evento,
    p_prioridad,
    p_hora_inicio,
    p_hora_fin,
    coalesce(p_recurrencia, 'Ninguna'),
    v_uid
  )
  RETURNING * INTO v_row;

  RETURN row_to_json(v_row);
END;
$$;

REVOKE ALL ON FUNCTION public.create_evento_calendario(integer, varchar, date, text, varchar, time, time, varchar) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.create_evento_calendario(integer, varchar, date, text, varchar, time, time, varchar) TO authenticated;

NOTIFY pgrst, 'reload schema';
